[package]
name = "subset-generator"
version = "0.1.0"
authors = ["satanja <s.a.tanja@student.tue.nl>"]
edition = "2018"
license = "MIT"
description = "Subset generator of a dataset"
repository = "https://github.com/satanja/subset_generator"
readme = "README.md"

[dependencies]
bit-vec = "*"
