[package]
name = "subset-generator"
version = "0.1.0"
authors = ["satanja <s.a.tanja@student.tue.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "*"